spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.springframework.security: info
    com.zaxxer.hikari: debug

management:
  endpoints:
    web:
      exposure:
        include: "health, info"

decorator:
  datasource:
    p6spy:
      enable-logging: false