spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org.springframework.security: trace
    com.zaxxer.hikari: debug

management:
  endpoints:
    web:
      exposure:
        include: "health, info"

jwt:
  secret: flip-secret-key-for-local-environment-please-update-to-a-secure-key
