spring :
  application:
    name: flipapp

  profiles:
    group:
      dev:
        - devdb
        - flyway
      local:
        - localdb
        - flyway
      test-local:
        - test
        - test-localdb
        - flyway
      test-github:
        - test
        - githubdb
        - flyway
    active: local
