spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org.springframework.security: trace
    com.zaxxer.hikari: debug

management:
  endpoints:
    web:
      exposure:
        include: "health, info"