ALTER TABLE profile
    ADD COLUMN following_cnt BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN follower_cnt BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN post_cnt BIGINT UNSIGNED NOT NULL DEFAULT 0;