name: dev server CD

on:
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: "backend/flip"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: dev
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      SHORT_SHA: ${{ github.sha::7 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with jib
        run: |
          ./gradlew jib \
          -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "flip-dev 배포 시작"
            IMAGE_ID=$(docker inspect --format '{{.Config.Image}}' flip-dev)
            docker rm flip-dev
            docker rmi $IMAGE_ID
            docker run --name flip-dev -d -p 8080:8080 ${{ env.DOCKERHUB_REPO }}:${{ env.SHORT_SHA }}
            echo "flip-dev 배포 완료"
